Fake news classifier using Bi-LSTM

In [13]:
import pandas as pd

In [42]:
df = pd.read_csv("/content/WELFake_Dataset.csv")

In [43]:
df.head()

,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Unnamed: 0,title,text,label
0,LAW ENFORCEMENT ON HIGH ALERT Following Threats Against Cops And Whites On 9-11By #BlackLivesMatter And #FYF911 Terrorists [VIDEO],"""No comment is expected from Barack Obama Members of the #FYF911 or #FukYoFlag and #BlackLivesMatter movements called for the lynching and hanging of white people and cops. They encouraged others on a radio show Tuesday night to turn the tide and kill white people and cops to send a message about the killing of black people in America.One of the F***YoFlag organizers is called Sunshine. She has a radio blog show hosted from Texas called",Sunshine s F***ing Opinion Radio Show. A snapshot of her #FYF911 @LOLatWhiteFear Twitter page at 9:53 p.m. shows that she was urging supporters to Call now!! #fyf911 tonight we continue to dismantle the illusion of white Below is a SNAPSHOT Twitter Radio Call Invite #FYF911The radio show aired at 10:00 p.m. eastern standard time.During the show,callers clearly call for lynching and killing of white people.A 2:39 minute clip from the radio show can be heard here. It was provided to Breitbart Texas by someone who would like to be referred to as Hannibal. He has already received death threats as a result of interrupting #FYF911 conference calls.An unidentified black man said when those mother f**kers are by themselves,that s when when we should start f***ing them up. Like they do us,when a bunch of them ni**ers takin one of us out,that s how we should roll up. He said,Cause we already roll up in gangs anyway. There should be six or seven black mother f**ckers,see that white person,and then lynch their ass. Let s turn the tables. They conspired that if cops started losing people,then there will be a state of emergency. He speculated that one of two things would happen,a big-ass [R s?????] war,or ni**ers,they are going to start backin up. We are already getting killed out here so what the f**k we got to lose? Sunshine could be heard saying,Yep,that s true. That s so f**king true. He said,We need to turn the tables on them. Our kids are getting shot out here. Somebody needs to become a sacrifice on their side.He said,Everybody ain t down for that s**t,or whatever,but like I say,everybody has a different position of war. He continued,Because they don t give a f**k anyway. He said again,We might as well utilized them for that s**t and turn the tables on these n**ers. He said,that way we can start lookin like we ain t havin that many casualties,and there can be more causalities on their side instead of ours. They are out their killing black people,black lives don t matter,that s what those mother f**kers so we got to make it matter to them. Find a mother f**ker that is alone. Snap his ass,and then f***in hang him from a damn tree. Take a picture of it and then send it to the mother f**kers. We just need one example,and then people will start watchin . This will turn the tables on s**t,he said. He said this will start a trickle-down effect. He said that when one white person is hung and then they are just flat-hanging,that will start the trickle-down effect. He continued,Black people are good at starting trends. He said that was how to get the upper-hand. Another black man spoke up saying they needed to kill cops that are killing us. The first black male said,That will be the best method right there. Breitbart Texas previously reported how Sunshine was upset when racist white people infiltrated and disrupted one of her conference calls. She subsequently released the phone number of one of the infiltrators. The veteran immediately started receiving threatening calls.One of the #F***YoFlag movement supporters allegedly told a veteran who infiltrated their publicly posted conference call,We are going to rape and gut your pregnant wife,and your f***ing piece of sh*t unborn creature will be hung from a tree. Breitbart Texas previously encountered Sunshine at a Sandra Bland protest at the Waller County Jail in Texas,where she said all white people should be killed. She told journalists and photographers,You see this nappy-ass hair on my head? That means I am one of those more militant Negroes. She said she was at the protest because these redneck mother-f**kers murdered Sandra Bland because she had nappy hair like me. #FYF911 black radicals say they will be holding the imperial powers that are actually responsible for the terrorist attacks on September 11th accountable on that day,as reported by Breitbart Texas. There are several websites and Twitter handles for the movement. Palmetto Star describes himself as one of the head organizers. He said in a YouTube video that supporters will be burning their symbols of the illusion of their superiority,their false white supremacy,like the American flag,the British flag,police uniforms,and Ku Klux Klan hoods.Sierra McGrone or Nocturnus Libertus posted,you too can help a young Afrikan clean their a** with the rag of oppression. She posted two photos,one that appears to be herself,and a photo of a black man,wiping their naked butts with the American fl...,1.0
1,NaN,Did they post their votes for Hillary already?,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MOST CHARLOTTE RIOTERS WERE “PEACEFUL” PROTESTERS…In Her Home State Of North Carolina [VIDEO],""" Now","most of the demonstrators gathered last night were exercising their constitutional and protected right to peaceful protest in order to raise issues and create change. Loretta Lynch aka Eric Holder in a skirt""",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"""Bobby Jindal",raised Hindu,"uses story of Christian conversion to woo evangelicals for potential 2016 bid""","""A dozen politically active pastors came here for a private dinner Friday night to hear a conversion story unique in the context of presidential politics: how Louisiana Gov. Bobby Jindal traveled from Hinduism to Protestant Christianity and",ultimately,became what he calls an “evangelical Catholic.”,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Over two hours,Jindal,42,recalled talking with a girl in high school who wanted to “save my soul,” reading the Bible in a closet so his parents would not see him and feeling a stir while watching a movie during his senior year that depicted Jesus on the cross.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df.drop("Unnamed: 0",axis=1,inplace=True)

In [21]:
df.isnull().sum()

title    57372
text     57446
label    57505
dtype: int64

In [22]:
df.shape

(57572, 3)

In [23]:
df=df.dropna()

In [24]:
df.head()

,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,title,text,label
0,LAW ENFORCEMENT ON HIGH ALERT Following Threats Against Cops And Whites On 9-11By #BlackLivesMatter And #FYF911 Terrorists [VIDEO],"""No comment is expected from Barack Obama Members of the #FYF911 or #FukYoFlag and #BlackLivesMatter movements called for the lynching and hanging of white people and cops. They encouraged others on a radio show Tuesday night to turn the tide and kill white people and cops to send a message about the killing of black people in America.One of the F***YoFlag organizers is called Sunshine. She has a radio blog show hosted from Texas called",Sunshine s F***ing Opinion Radio Show. A snapshot of her #FYF911 @LOLatWhiteFear Twitter page at 9:53 p.m. shows that she was urging supporters to Call now!! #fyf911 tonight we continue to dismantle the illusion of white Below is a SNAPSHOT Twitter Radio Call Invite #FYF911The radio show aired at 10:00 p.m. eastern standard time.During the show,callers clearly call for lynching and killing of white people.A 2:39 minute clip from the radio show can be heard here. It was provided to Breitbart Texas by someone who would like to be referred to as Hannibal. He has already received death threats as a result of interrupting #FYF911 conference calls.An unidentified black man said when those mother f**kers are by themselves,that s when when we should start f***ing them up. Like they do us,when a bunch of them ni**ers takin one of us out,that s how we should roll up. He said,Cause we already roll up in gangs anyway. There should be six or seven black mother f**ckers,see that white person,and then lynch their ass. Let s turn the tables. They conspired that if cops started losing people,then there will be a state of emergency. He speculated that one of two things would happen,a big-ass [R s?????] war,or ni**ers,they are going to start backin up. We are already getting killed out here so what the f**k we got to lose? Sunshine could be heard saying,Yep,that s true. That s so f**king true. He said,We need to turn the tables on them. Our kids are getting shot out here. Somebody needs to become a sacrifice on their side.He said,Everybody ain t down for that s**t,or whatever,but like I say,everybody has a different position of war. He continued,Because they don t give a f**k anyway. He said again,We might as well utilized them for that s**t and turn the tables on these n**ers. He said,that way we can start lookin like we ain t havin that many casualties,and there can be more causalities on their side instead of ours. They are out their killing black people,black lives don t matter,that s what those mother f**kers so we got to make it matter to them. Find a mother f**ker that is alone. Snap his ass,and then f***in hang him from a damn tree. Take a picture of it and then send it to the mother f**kers. We just need one example,and then people will start watchin . This will turn the tables on s**t,he said. He said this will start a trickle-down effect. He said that when one white person is hung and then they are just flat-hanging,that will start the trickle-down effect. He continued,Black people are good at starting trends. He said that was how to get the upper-hand. Another black man spoke up saying they needed to kill cops that are killing us. The first black male said,That will be the best method right there. Breitbart Texas previously reported how Sunshine was upset when racist white people infiltrated and disrupted one of her conference calls. She subsequently released the phone number of one of the infiltrators. The veteran immediately started receiving threatening calls.One of the #F***YoFlag movement supporters allegedly told a veteran who infiltrated their publicly posted conference call,We are going to rape and gut your pregnant wife,and your f***ing piece of sh*t unborn creature will be hung from a tree. Breitbart Texas previously encountered Sunshine at a Sandra Bland protest at the Waller County Jail in Texas,where she said all white people should be killed. She told journalists and photographers,You see this nappy-ass hair on my head? That means I am one of those more militant Negroes. She said she was at the protest because these redneck mother-f**kers murdered Sandra Bland because she had nappy hair like me. #FYF911 black radicals say they will be holding the imperial powers that are actually responsible for the terrorist attacks on September 11th accountable on that day,as reported by Breitbart Texas. There are several websites and Twitter handles for the movement. Palmetto Star describes himself as one of the head organizers. He said in a YouTube video that supporters will be burning their symbols of the illusion of their superiority,their false white supremacy,like the American flag,the British flag,police uniforms,and Ku Klux Klan hoods.Sierra McGrone or Nocturnus Libertus posted,you too can help a young Afrikan clean their a** with the rag of oppression. She posted two photos,and a photo of a black man,wiping their naked butts with the American fl...,1.0
141,Poll Finds Voters in Both Parties Unhappy With Their Candidates - The New York Times,"""On the eve of the major party conventions",voters are grudgingly rallying around the nominees while expressing broad misgivings about the candidates,the campaign and the direction of the country,according to the latest New York News Poll. More than a third of Republicans say they are disappointed or upset that Donald J. Trump,who crashed the party’s nominating process,will represent them in the fall campaign an equal number say he does not represent the values the party should stand for. Democrats are only marginally happier with Hillary Clinton as their party’s candidate. A quarter of Democratic voters say they are disappointed in her as the nominee an additional seven percent say they are upset. More promisingly for her,say Mrs. Clinton stands for the core values and principles of the Democratic Party. The broad discontent is reflected in the contest,which has Mr. Trump and Mrs. Clinton tied at 40 percent. Mr. Trump’s standing has held steady for weeks at around 40 percentage points,while Mrs. Clinton has polled in the in most public surveys. The latest News Poll was conducted after the F. B. I. rebuked her for her email practices but before Bernie Sanders,her persistent primary rival,embraced and endorsed her this week. So the dip in her standing could be temporary and reverse sharply if the Democrats,who are far more united as a party than the Republicans,pull off a successful convention in Philadelphia. In a development not seen in any modern presidential contest,more than half of all voters hold unfavorable views of the two major party candidates and large majorities say neither is honest and trustworthy. Only half of voters say Mrs. Clinton is prepared to be president,while an astonishing say that Mr. Trump is not ready for the job — including four in 10 Republicans. Peter Lieb,54,a middle school history teacher in West Palm Beach,Fla. voted for Gov. John Kasich of Ohio in the Florida primary and said in a interview that he was only reluctantly planning to vote for Mr. Trump in November. Why Mr. Trump? “Honestly?” Mr. Lieb said. “Last man standing. ” “I am not a supporter of Donald Trump,but given the alternatives that I’m presented with,he is the best person for the task at hand,” he said. “And the task at hand in my opinion is regaining economic stability and regaining America’s stature in the world. I don’t see Hillary Clinton doing a constructive job in either. ” The nationwide poll was conducted July on cellphones and landlines among 1,358 registered voters. The margin of sampling error is plus or minus three percentage points for all voters. Preconvention polls are often erratic,and political analysts and campaign managers put more stock in polls taken after both parties have formally nominated their candidates. And national polls,while useful as a gauge of broad sentiment,are less reliable than state polls in predicting the ultimate outcome. Mrs. Clinton enjoys strong advantages in many of the swing states she will need to secure victory in the Electoral College. Mrs. Clinton still leads in averages of recent polls,though her margin has narrowed since late June. The latest News poll could be an indication of an even tighter race. Yet Mr. Trump has not led a national poll that meets The Times’s polling standards since just after he won enough delegates to secure the Republican nomination. While the race may be narrow,the gloom appears broad. Rachel Woolard,20,of Jacksonville,Fla. supported Mr. Sanders in the primary but now says she will,with misgivings,probably vote for Mrs. Clinton. “Bernie seemed to be more transparent than her,” said Ms. Woolard,a college student. “She definitely has the stereotypical politician approach to things,so that makes her feel a little disingenuous. ” Ms. Woolard is not yet fully committed to voting for Mrs. Clinton. But she knows whom she is voting against. “I know for a fact that I’m not voting for Trump. ” Laura Schrock,36,a homemaker and political independent in Greenwood,Del. said she will not vote for Mr. Trump or Mrs. Clinton. “At this point,the plan is to vote for the Libertarian candidate,” she said,referring to Gary Johnson. “I highly value being real and being very honest. And I’m just not getting that from either one. ” In a contest,Mr. Johnson has 12 percent,while Mr. Trump and Mrs. Clinton are tied with 36 percent. Republicans and Democrats are divided by more than political philosophy and their choice of presidential candidates. They hold very different views of the state of the nation,however. Six in 10 Republicans,Democrats and independents say they are not l...,0.0
274,BREAKING: CLINTON CHAIRMAN’S SISTER-IN-LAW Lobbied Clinton’s State Department…Earned Six Figure Income,"""Amid the tumult of the 2016 presidential campaign",John Podesta is best known as Hillary Clinton s campaign chairman and the individual from whose private account WikiLeaks is presently publishing some 50,000 hacked emails.Released in daily batches,these documents have laid bare the inner workings and tensions of the Clinton campaign in an unprecedented way,while also offering insights into the operations of the Clinton Foundation and the State Department in the years when Clinton,now the Democratic presidential nominee,served as secretary of state.At that time,when Clinton was traveling to a record number of foreign countries,Podesta,a former White House chief of staff under President Clinton,held dual titles at the State Department: as a senior advisor entitled to an annual salary of $130,000 never paid him,the department maintains and as a member of a prestigious foreign policy advisory board Secretary Clinton created. Records obtained from the U.S. Office of Personnel Management show Podesta s tenure at State extended from Sept. 25,2011 to Jan. 4,2014.For several months in 2012,Clinton s final year as secretary of state,Raytheon,the leading defense contractor,hired Podesta s sister-in-law,Heather Podesta,as a lobbyist,federal records show.Raytheon was looking to enlarge its share of foreign military sales transfers of advanced weapons systems to other countries that are reviewed and approved by the Department of State,then implemented by the Department of Defense and was beefing up its lobbying operation to accomplish that goal before Secretary Clinton left office.On the LD-2 lobbying disclosure form completed by her company,Heather Podesta + Partners,LLC,in July 2012,the veteran lawyer and Democratic fundraiser listed in the space provided for a description of her lobbying activities,Engaged the Executive Branch on the economic benefits of foreign military sales. In the space requesting the specific locales of her lobbying,Ms. Podesta listed the White House and the State Department.At the same time,Raytheon retained two other lobbyists,John Merrigan and Matt Bernstein,both associated with the powerhouse D.C. law firm DLA Piper. All three of these lobbyists,including Ms. Podesta,were major donors or bundlers to Hillary Clinton s 2008 and 2016 campaigns. Federal records show they have raised hundreds of thousands of dollars for Clinton s campaigns and earned hundreds of thousands of dollars lobbying her State Department.In the final three quarters of 2012,DLA Piper earned some $360,000 in lobbying fees from Raytheon,courting the State Department and other agencies,while Ms. Podesta,within that same time frame,received $100,000 from Raytheon for the same purpose.The gambit appears to have worked: Records maintained by the Defense Security Cooperation Agency,the arm of the Defense Department that coordinates the transfers of weapons systems once they have received State s approval,show Raytheon as a prime contractor in at least seventeen foreign military sales in 2012,three with the Gulf nation of Qatar for mis...,Apache attack helicopters and other materiel ...,1.0
570,HILLARY’S STATE DEPARTMENT BLOCKED Min Wage Hike For Haiti’s Poorest Citizens To Keep Costs Down For U.S. Owned Factories,"""Corporations first Unfortunately",the poor factory worker in Haiti couldn t help Hillary or her campaign Hillary But just ask her,she ll tell you she s always looking out for the little guy! So much for the champion of the factory worker or the champion of the poor In Haiti,people work for peanuts. Slave wages. Less than $5 per day,but they supply the U.S. with tons of affordable clothing from big-name brands like Levi s,Hanes and Polo. Haiti s big advantage,compared to Asia,is their proximity to us,and thousands of Haitians are employed in the textile industry in part because of that. When Haiti passed a wage raise from $.24 per hour to $.61 per hour,American companies were predictably outraged.Enter Hillary s State Department Hillary Clinton colluded with big business to maintain slave wages for workers in one of the world s poorest countries,according to the host of an RT American comedy news show.Comedian and activist Lee Camp of RT s Redacted Tonight mocked Clinton s efforts to keep 37 cents per hour out of the hands of destitute Haitians. In 2009,while Bill Clinton was setting up one of the family s shell companies in New York,in that same year Hillary Clinton was at the State Department working with U.S. corporations to pressure Haiti not to raise the minimum wage to 61 cents an hour from 24 cents,Camp said April 17. Seriously. Memos from 2008 and 2009 obtained by Wikileaks strongly suggest,but don t prove without a doubt,that the State Department helped block the proposed minimum wage increase. The memos show that U.S. Embassy officials in Haiti clearly opposed the wage hike and met multiple times with factory owners who directly lobbied against it to the Haitian president.The Clinton campaign (as expected) refuted the claim,and the State Department didn t comment.- PolitifactThis took place in 2011,and Hillary Clinton was the Secretary of State. Our corporations were successful,and Haitians continued to work for worse slave wages than they otherwise would have,all so U.S. corporations could take home higher profits.At the time,the U.S. Embassy said that the wage increase didn t take economic realities into account,and that it was a move designed specifically to appeal to the unemployed and underpaid masses of Haiti. Imagine that. Imagine trying to help your people have a better life instead of catering to huge corporations at your people s expense. The horror. News.groopspeakHOPE,not changeIn 2011,Wikileaks made nearly 2,000 cables available to the progressive magazine,The Nation,and Haiti Libert,a weekly newspaper in Port-au-Prince.The two media outlets assessed the cables and found,among many other revelations,that the U.S. Embassy in Haiti worked closely with factory owners contracted by Levi s,Hanes,and Fruit of the Loom to aggressively block a paltry minimum wage increase for workers in apparel factories.The Wikileaks cables show U.S. Embassy officials began monitoring the minimum wage issue as early as 2008,when the Haitian Parliament began discussing doubling or tripling the daily minimum wage of 70 Haitian gourdes to keep up with inflation. That s roughly equal to $1.75 a day,or about 22 cents per hour.(Some context here: Three quarters of Haitians live on less than $2 a day,according to the United Nations World Food Program,while garments constitute about 90 percent of Haiti s exports,according to the Guardian. Haiti increased the daily minimum wage to the equivalent of $5.11 in 2014.)But back in 2008 and 2009,embassy officials repeatedly told Washington that a hike would hurt the economy and undermine U.S. trade preference legislation known as HOPE.The program,shorthand for the Haitian Hemispheric Opportunity through Partnership Encouragement Act of 2006,gives garments manufactured on the island duty free access to U.S. markets. Levi Strauss,Haneswear,Nautica,and Dockers are just some of the American companies that benefit from HOPE. Congress passed HOPE II in 2008,Ambassador Janet Sanderson wrote that represe...,charg d affaires Thomas Tighe told the diplo...,1.0

In [25]:
# Get independent features
x=df.drop('label', axis=1)

In [26]:
y=df['label']

In [27]:
# check whether dataset is balanced or not
y.value_counts()

label
0.0    44
1.0    23
Name: count, dtype: int64

In [28]:
import tensorflow as tf

In [29]:
tf.__version__

'2.19.0'

In [30]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense , Bidirectional , Input

In [31]:
voc_size=1000

In [32]:
messages=x.copy()

In [33]:
messages

,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,title,text
0,LAW ENFORCEMENT ON HIGH ALERT Following Threats Against Cops And Whites On 9-11By #BlackLivesMatter And #FYF911 Terrorists [VIDEO],"""No comment is expected from Barack Obama Members of the #FYF911 or #FukYoFlag and #BlackLivesMatter movements called for the lynching and hanging of white people and cops. They encouraged others on a radio show Tuesday night to turn the tide and kill white people and cops to send a message about the killing of black people in America.One of the F***YoFlag organizers is called Sunshine. She has a radio blog show hosted from Texas called",Sunshine s F***ing Opinion Radio Show. A snapshot of her #FYF911 @LOLatWhiteFear Twitter page at 9:53 p.m. shows that she was urging supporters to Call now!! #fyf911 tonight we continue to dismantle the illusion of white Below is a SNAPSHOT Twitter Radio Call Invite #FYF911The radio show aired at 10:00 p.m. eastern standard time.During the show,callers clearly call for lynching and killing of white people.A 2:39 minute clip from the radio show can be heard here. It was provided to Breitbart Texas by someone who would like to be referred to as Hannibal. He has already received death threats as a result of interrupting #FYF911 conference calls.An unidentified black man said when those mother f**kers are by themselves,that s when when we should start f***ing them up. Like they do us,when a bunch of them ni**ers takin one of us out,that s how we should roll up. He said,Cause we already roll up in gangs anyway. There should be six or seven black mother f**ckers,see that white person,and then lynch their ass. Let s turn the tables. They conspired that if cops started losing people,then there will be a state of emergency. He speculated that one of two things would happen,a big-ass [R s?????] war,or ni**ers,they are going to start backin up. We are already getting killed out here so what the f**k we got to lose? Sunshine could be heard saying,Yep,that s true. That s so f**king true. He said,We need to turn the tables on them. Our kids are getting shot out here. Somebody needs to become a sacrifice on their side.He said,Everybody ain t down for that s**t,or whatever,but like I say,everybody has a different position of war. He continued,Because they don t give a f**k anyway. He said again,We might as well utilized them for that s**t and turn the tables on these n**ers. He said,that way we can start lookin like we ain t havin that many casualties,and there can be more causalities on their side instead of ours. They are out their killing black people,black lives don t matter,that s what those mother f**kers so we got to make it matter to them. Find a mother f**ker that is alone. Snap his ass,and then f***in hang him from a damn tree. Take a picture of it and then send it to the mother f**kers. We just need one example,and then people will start watchin . This will turn the tables on s**t,he said. He said this will start a trickle-down effect. He said that when one white person is hung and then they are just flat-hanging,that will start the trickle-down effect. He continued,Black people are good at starting trends. He said that was how to get the upper-hand. Another black man spoke up saying they needed to kill cops that are killing us. The first black male said,That will be the best method right there. Breitbart Texas previously reported how Sunshine was upset when racist white people infiltrated and disrupted one of her conference calls. She subsequently released the phone number of one of the infiltrators. The veteran immediately started receiving threatening calls.One of the #F***YoFlag movement supporters allegedly told a veteran who infiltrated their publicly posted conference call,We are going to rape and gut your pregnant wife,and your f***ing piece of sh*t unborn creature will be hung from a tree. Breitbart Texas previously encountered Sunshine at a Sandra Bland protest at the Waller County Jail in Texas,where she said all white people should be killed. She told journalists and photographers,You see this nappy-ass hair on my head? That means I am one of those more militant Negroes. She said she was at the protest because these redneck mother-f**kers murdered Sandra Bland because she had nappy hair like me. #FYF911 black radicals say they will be holding the imperial powers that are actually responsible for the terrorist attacks on September 11th accountable on that day,as reported by Breitbart Texas. There are several websites and Twitter handles for the movement. Palmetto Star describes himself as one of the head organizers. He said in a YouTube video that supporters will be burning their symbols of the illusion of their superiority,their false white supremacy,like the American flag,the British flag,police uniforms,and Ku Klux Klan hoods.Sierra McGrone or Nocturnus Libertus posted,you too can help a young Afrikan clean their a** with the rag of oppression. She posted two photos,and a photo of a black man,wiping their naked butts with the American fl...
141,Poll Finds Voters in Both Parties Unhappy With Their Candidates - The New York Times,"""On the eve of the major party conventions",voters are grudgingly rallying around the nominees while expressing broad misgivings about the candidates,the campaign and the direction of the country,according to the latest New York News Poll. More than a third of Republicans say they are disappointed or upset that Donald J. Trump,who crashed the party’s nominating process,will represent them in the fall campaign an equal number say he does not represent the values the party should stand for. Democrats are only marginally happier with Hillary Clinton as their party’s candidate. A quarter of Democratic voters say they are disappointed in her as the nominee an additional seven percent say they are upset. More promisingly for her,say Mrs. Clinton stands for the core values and principles of the Democratic Party. The broad discontent is reflected in the contest,which has Mr. Trump and Mrs. Clinton tied at 40 percent. Mr. Trump’s standing has held steady for weeks at around 40 percentage points,while Mrs. Clinton has polled in the in most public surveys. The latest News Poll was conducted after the F. B. I. rebuked her for her email practices but before Bernie Sanders,her persistent primary rival,embraced and endorsed her this week. So the dip in her standing could be temporary and reverse sharply if the Democrats,who are far more united as a party than the Republicans,pull off a successful convention in Philadelphia. In a development not seen in any modern presidential contest,more than half of all voters hold unfavorable views of the two major party candidates and large majorities say neither is honest and trustworthy. Only half of voters say Mrs. Clinton is prepared to be president,while an astonishing say that Mr. Trump is not ready for the job — including four in 10 Republicans. Peter Lieb,54,a middle school history teacher in West Palm Beach,Fla. voted for Gov. John Kasich of Ohio in the Florida primary and said in a interview that he was only reluctantly planning to vote for Mr. Trump in November. Why Mr. Trump? “Honestly?” Mr. Lieb said. “Last man standing. ” “I am not a supporter of Donald Trump,but given the alternatives that I’m presented with,he is the best person for the task at hand,” he said. “And the task at hand in my opinion is regaining economic stability and regaining America’s stature in the world. I don’t see Hillary Clinton doing a constructive job in either. ” The nationwide poll was conducted July on cellphones and landlines among 1,358 registered voters. The margin of sampling error is plus or minus three percentage points for all voters. Preconvention polls are often erratic,and political analysts and campaign managers put more stock in polls taken after both parties have formally nominated their candidates. And national polls,while useful as a gauge of broad sentiment,are less reliable than state polls in predicting the ultimate outcome. Mrs. Clinton enjoys strong advantages in many of the swing states she will need to secure victory in the Electoral College. Mrs. Clinton still leads in averages of recent polls,though her margin has narrowed since late June. The latest News poll could be an indication of an even tighter race. Yet Mr. Trump has not led a national poll that meets The Times’s polling standards since just after he won enough delegates to secure the Republican nomination. While the race may be narrow,the gloom appears broad. Rachel Woolard,20,of Jacksonville,Fla. supported Mr. Sanders in the primary but now says she will,with misgivings,probably vote for Mrs. Clinton. “Bernie seemed to be more transparent than her,” said Ms. Woolard,a college student. “She definitely has the stereotypical politician approach to things,so that makes her feel a little disingenuous. ” Ms. Woolard is not yet fully committed to voting for Mrs. Clinton. But she knows whom she is voting against. “I know for a fact that I’m not voting for Trump. ” Laura Schrock,36,a homemaker and political independent in Greenwood,Del. said she will not vote for Mr. Trump or Mrs. Clinton. “At this point,the plan is to vote for the Libertarian candidate,” she said,referring to Gary Johnson. “I highly value being real and being very honest. And I’m just not getting that from either one. ” In a contest,Mr. Johnson has 12 percent,while Mr. Trump and Mrs. Clinton are tied with 36 percent. Republicans and Democrats are divided by more than political philosophy and their choice of presidential candidates. They hold very different views of the state of the nation,however. Six in 10 Republicans,Democrats and independents say they are not l...
274,BREAKING: CLINTON CHAIRMAN’S SISTER-IN-LAW Lobbied Clinton’s State Department…Earned Six Figure Income,"""Amid the tumult of the 2016 presidential campaign",John Podesta is best known as Hillary Clinton s campaign chairman and the individual from whose private account WikiLeaks is presently publishing some 50,000 hacked emails.Released in daily batches,these documents have laid bare the inner workings and tensions of the Clinton campaign in an unprecedented way,while also offering insights into the operations of the Clinton Foundation and the State Department in the years when Clinton,now the Democratic presidential nominee,served as secretary of state.At that time,when Clinton was traveling to a record number of foreign countries,Podesta,a former White House chief of staff under President Clinton,held dual titles at the State Department: as a senior advisor entitled to an annual salary of $130,000 never paid him,the department maintains and as a member of a prestigious foreign policy advisory board Secretary Clinton created. Records obtained from the U.S. Office of Personnel Management show Podesta s tenure at State extended from Sept. 25,2011 to Jan. 4,2014.For several months in 2012,Clinton s final year as secretary of state,Raytheon,the leading defense contractor,hired Podesta s sister-in-law,Heather Podesta,as a lobbyist,federal records show.Raytheon was looking to enlarge its share of foreign military sales transfers of advanced weapons systems to other countries that are reviewed and approved by the Department of State,then implemented by the Department of Defense and was beefing up its lobbying operation to accomplish that goal before Secretary Clinton left office.On the LD-2 lobbying disclosure form completed by her company,Heather Podesta + Partners,LLC,in July 2012,the veteran lawyer and Democratic fundraiser listed in the space provided for a description of her lobbying activities,Engaged the Executive Branch on the economic benefits of foreign military sales. In the space requesting the specific locales of her lobbying,Ms. Podesta listed the White House and the State Department.At the same time,Raytheon retained two other lobbyists,John Merrigan and Matt Bernstein,both associated with the powerhouse D.C. law firm DLA Piper. All three of these lobbyists,including Ms. Podesta,were major donors or bundlers to Hillary Clinton s 2008 and 2016 campaigns. Federal records show they have raised hundreds of thousands of dollars for Clinton s campaigns and earned hundreds of thousands of dollars lobbying her State Department.In the final three quarters of 2012,DLA Piper earned some $360,000 in lobbying fees from Raytheon,courting the State Department and other agencies,while Ms. Podesta,within that same time frame,received $100,000 from Raytheon for the same purpose.The gambit appears to have worked: Records maintained by the Defense Security Cooperation Agency,the arm of the Defense Department that coordinates the transfers of weapons systems once they have received State s approval,show Raytheon as a prime contractor in at least seventeen foreign military sales in 2012,three with the Gulf nation of Qatar for mis...,Apache attack helicopters and other materiel ...
570,HILLARY’S STATE DEPARTMENT BLOCKED Min Wage Hike For Haiti’s Poorest Citizens To Keep Costs Down For U.S. Owned Factories,"""Corporations first Unfortunately",the poor factory worker in Haiti couldn t help Hillary or her campaign Hillary But just ask her,she ll tell you she s always looking out for the little guy! So much for the champion of the factory worker or the champion of the poor In Haiti,people work for peanuts. Slave wages. Less than $5 per day,but they supply the U.S. with tons of affordable clothing from big-name brands like Levi s,Hanes and Polo. Haiti s big advantage,compared to Asia,is their proximity to us,and thousands of Haitians are employed in the textile industry in part because of that. When Haiti passed a wage raise from $.24 per hour to $.61 per hour,American companies were predictably outraged.Enter Hillary s State Department Hillary Clinton colluded with big business to maintain slave wages for workers in one of the world s poorest countries,according to the host of an RT American comedy news show.Comedian and activist Lee Camp of RT s Redacted Tonight mocked Clinton s efforts to keep 37 cents per hour out of the hands of destitute Haitians. In 2009,while Bill Clinton was setting up one of the family s shell companies in New York,in that same year Hillary Clinton was at the State Department working with U.S. corporations to pressure Haiti not to raise the minimum wage to 61 cents an hour from 24 cents,Camp said April 17. Seriously. Memos from 2008 and 2009 obtained by Wikileaks strongly suggest,but don t prove without a doubt,that the State Department helped block the proposed minimum wage increase. The memos show that U.S. Embassy officials in Haiti clearly opposed the wage hike and met multiple times with factory owners who directly lobbied against it to the Haitian president.The Clinton campaign (as expected) refuted the claim,and the State Department didn t comment.- PolitifactThis took place in 2011,and Hillary Clinton was the Secretary of State. Our corporations were successful,and Haitians continued to work for worse slave wages than they otherwise would have,all so U.S. corporations could take home higher profits.At the time,the U.S. Embassy said that the wage increase didn t take economic realities into account,and that it was a move designed specifically to appeal to the unemployed and underpaid masses of Haiti. Imagine that. Imagine trying to help your people have a better life instead of catering to huge corporations at your people s expense. The horror. News.groopspeakHOPE,not changeIn 2011,Wikileaks made nearly 2,000 cables available to the progressive magazine,The Nation,and Haiti Libert,a weekly newspaper in Port-au-Prince.The two media outlets assessed the cables and found,among many other revelations,that the U.S. Embassy in Haiti worked closely with factory owners contracted by Levi s,Hanes,and Fruit of the Loom to aggressively block a paltry minimum wage increase for workers in apparel factories.The Wikileaks cables show U.S. Embassy officials began monitoring the minimum wage issue as early as 2008,when the Haitian Parliament began discussing doubling or tripling the daily minimum wage of 70 Haitian gourdes to keep up with inflation. That s roughly equal to $1.75 a day,or about 22 cents per hour.(Some context here: Three quarters of Haitians live on less than $2 a day,according to the United Nations World Food Program,while garments constitute about 90 percent of Haiti s exports,according to the Guardian. Haiti increased the daily minimum wage to the equivalent of $5.11 in 2014.)But back in 2008 and 2009,embassy officials repeatedly told Washington that a hike would hurt the economy and undermine U.S. trade preference legislation known as HOPE.The program,shorthand for the Haitian Hemispheric Opportunity through Partnership Encouragement Act of 2006,gives garments manufactured on the island duty free access to U.S. markets. Levi Strauss,Haneswear,Nautica,and Dockers are just some of the American companies that benefit from HOPE. Congress passed HOPE II in 2008,Ambassador Janet Sanderson wrote that represe...,charg d affaires Thomas Tighe told the diplo...

In [34]:
import nltk

In [35]:
import re
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [36]:
# Dataset preperocessing
# porter stemmer
from nltk.stem.porter import PorterStemmer

In [37]:
ps=PorterStemmer()
corpus=[]
for i in range (0 , len(messages)):
  print(i)
  review=re.sub('[^a-zA-Z]',' ',messages['title'][i])
  review=review.lower()
  review=review.split()

  review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66

/tmp/ipython-input-3457495279.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  review=re.sub('[^a-zA-Z]',' ',messages['title'][i])