In [1]:
import pandas as pd

## best practices
1. Preprocessing and cleaning
2. Train test split
3. BOW TFIDF word2vec
4. Train ML algorithms

In [2]:
df= pd.read_csv('kindle_reviews.csv')

In [3]:
df.head()

,Unnamed: 0,asin,helpful,overall,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,B000F83SZQ,"[0, 0]",5,I enjoy vintage books and movies so I enjoyed ...,"05 5, 2014",A1F6404F1VG29J,Avidreader,Nice vintage story,1399248000
1,1,B000F83SZQ,"[2, 2]",4,This book is a reissue of an old one; the auth...,"01 6, 2014",AN0N05A9LIJEQ,critters,Different...,1388966400
2,2,B000F83SZQ,"[2, 2]",4,This was a fairly interesting read. It had ol...,"04 4, 2014",A795DMNCJILA6,dot,Oldie,1396569600
3,3,B000F83SZQ,"[1, 1]",5,I'd never read any of the Amy Brewster mysteri...,"02 19, 2014",A1FV0SX13TWVXQ,"Elaine H. Turley ""Montana Songbird""",I really liked it.,1392768000
4,4,B000F83SZQ,"[0, 1]",4,"If you like period pieces - clothing, lingo, y...","03 19, 2014",A3SPTOKDG7WBLN,Father Dowling Fan,Period Mystery,1395187200

In [4]:
df.drop('Unnamed: 0', axis=1 , inplace=True)

In [5]:
df.head()

,asin,helpful,overall,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,B000F83SZQ,"[0, 0]",5,I enjoy vintage books and movies so I enjoyed ...,"05 5, 2014",A1F6404F1VG29J,Avidreader,Nice vintage story,1399248000
1,B000F83SZQ,"[2, 2]",4,This book is a reissue of an old one; the auth...,"01 6, 2014",AN0N05A9LIJEQ,critters,Different...,1388966400
2,B000F83SZQ,"[2, 2]",4,This was a fairly interesting read. It had ol...,"04 4, 2014",A795DMNCJILA6,dot,Oldie,1396569600
3,B000F83SZQ,"[1, 1]",5,I'd never read any of the Amy Brewster mysteri...,"02 19, 2014",A1FV0SX13TWVXQ,"Elaine H. Turley ""Montana Songbird""",I really liked it.,1392768000
4,B000F83SZQ,"[0, 1]",4,"If you like period pieces - clothing, lingo, y...","03 19, 2014",A3SPTOKDG7WBLN,Father Dowling Fan,Period Mystery,1395187200

In [6]:
data= df[['reviewText' , 'overall']]
data

                                               reviewText  overall
0       I enjoy vintage books and movies so I enjoyed ...        5
1       This book is a reissue of an old one; the auth...        4
2       This was a fairly interesting read.  It had ol...        4
3       I'd never read any of the Amy Brewster mysteri...        5
4       If you like period pieces - clothing, lingo, y...        4
...                                                   ...      ...
982614  Yasss hunny! This is a great read. That Dre is...        5
982615  I ENJOYED THIS BOOK FROM BEGINNING TO END NOW ...        5
982616  Great book! Cherika was a fool. She let that m...        5
982617  When I say this was an excellent book please b...        5
982618  This book was everything. I just hope Alexus w...        5

[982619 rows x 2 columns]

In [7]:
data.shape

(982619, 2)

In [8]:
# Missing values
data.isnull().sum()

reviewText    22
overall        0
dtype: int64

In [9]:
# Check unique rating
data['overall'].unique()

array([5, 4, 3, 2, 1], dtype=int64)

In [10]:
# Check number of ratings
data['overall'].value_counts()

overall
5    575264
4    254013
3     96194
2     34130
1     23018
Name: count, dtype: int64

In [11]:
data.head()

                                          reviewText  overall
0  I enjoy vintage books and movies so I enjoyed ...        5
1  This book is a reissue of an old one; the auth...        4
2  This was a fairly interesting read.  It had ol...        4
3  I'd never read any of the Amy Brewster mysteri...        5
4  If you like period pieces - clothing, lingo, y...        4

In [12]:
# Preprocessing and cleaning 
data['overall']=data['overall'].apply(lambda x:0 if x<3 else 1)

C:\Users\sawan\AppData\Local\Temp\ipykernel_1720\893010650.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['overall']=data['overall'].apply(lambda x:0 if x<3 else 1)

In [13]:
data

                                               reviewText  overall
0       I enjoy vintage books and movies so I enjoyed ...        1
1       This book is a reissue of an old one; the auth...        1
2       This was a fairly interesting read.  It had ol...        1
3       I'd never read any of the Amy Brewster mysteri...        1
4       If you like period pieces - clothing, lingo, y...        1
...                                                   ...      ...
982614  Yasss hunny! This is a great read. That Dre is...        1
982615  I ENJOYED THIS BOOK FROM BEGINNING TO END NOW ...        1
982616  Great book! Cherika was a fool. She let that m...        1
982617  When I say this was an excellent book please b...        1
982618  This book was everything. I just hope Alexus w...        1

[982619 rows x 2 columns]

In [14]:
data['overall'].unique()

array([1, 0], dtype=int64)

In [15]:
data['overall'].value_counts()

overall
1    925471
0     57148
Name: count, dtype: int64

In [16]:
# Lowe all the upper cases
data['reviewText']=data['reviewText'].str.lower()

C:\Users\sawan\AppData\Local\Temp\ipykernel_1720\3017776927.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['reviewText']=data['reviewText'].str.lower()

In [17]:
data.head()

                                          reviewText  overall
0  i enjoy vintage books and movies so i enjoyed ...        1
1  this book is a reissue of an old one; the auth...        1
2  this was a fairly interesting read.  it had ol...        1
3  i'd never read any of the amy brewster mysteri...        1
4  if you like period pieces - clothing, lingo, y...        1

In [18]:
data.dtypes

reviewText    object
overall        int64
dtype: object

In [19]:
data['reviewText']=data['reviewText'].astype(str)

C:\Users\sawan\AppData\Local\Temp\ipykernel_1720\1495181082.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['reviewText']=data['reviewText'].astype(str)

In [20]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words= set(stopwords.words('english'))
import re

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sawan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [21]:
from bs4 import BeautifulSoup

In [22]:
df=data

In [23]:
df.shape

(982619, 2)

In [24]:
df['overall'].value_counts()

overall
1    925471
0     57148
Name: count, dtype: int64

In [ ]:
## Removing special characters
df['reviewText'] = df['reviewText'].apply(lambda x: re.sub('[^a-z A-Z 0-9]+', ' ', x))

## Remove the stopwords
df['reviewText'] = df['reviewText'].apply(lambda x: " ".join([y for y in x.split() if y not in stop_words]))

## Remove url
df['reviewText']=df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))', '', x))

## Remove html tags
df['reviewText']=df['reviewText'].apply(lambda x: BeautifulSoup(x, 'html.parser').get_text())

## Remove any additional spaces
df['reviewText'] = df['reviewText'].apply(lambda x: " ".join(x.split()))

In [26]:
df.head()

                                          reviewText  overall
0  i enjoy vintage books and movies so i enjoyed ...        1
1  this book is a reissue of an old one; the auth...        1
2  this was a fairly interesting read.  it had ol...        1
3  i'd never read any of the amy brewster mysteri...        1
4  if you like period pieces - clothing, lingo, y...        1

In [ ]:
df.to_csv('data_processed.csv')